version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    networks:
      - server

  serverGRPC:
    container_name: serverGRPC
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - mongodb:mongo
    environment:
      - DEBUG=true
    ports:
      - "50051:50051"
    depends_on:
      - mongodb
    networks:
      - serverGRPC
    tty: true

  serverHTTP:
    container_name: serverHTTP
    restart: always
    links:
      - mongodb:mongo
    environment:
      - DEBUG=true
    ports:
      - "4112:4112"
    depends_on:
      - mongodb
    networks:
      - serverHTTP
    tty: true

networks:
  server:



