version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - mongodb:mongo
    environment:
      - DEBUG=true
    ports:
      - "50051:50051"
      - "4112:4112"
    depends_on:
      - mongodb
    tty: true